[project]
name = "cfn-resource-provider-schemas"
version = "25.5.1"
description = "AWS CFN Resource Properties JSON Schema definitions"
requires-python = ">=3.11"
dependencies = []
authors = [
  { name="Stefan Heitmüller", email="stefan.heitmueller@gmx.com" }
]
readme = "README.md"
repository = "https://gitlab.com/morph027/cfn-resource-provider-schemas"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
artifacts = [
  "/schemas/*.json"
]
